algo_args:
  algo:
    clip_param: 0.2
    entropy_coef: 0.01
    gae_lambda: 0.95
    gamma: 0.99
    huber_delta: 10.0
    max_grad_norm: 10.0
    num_mini_batch: 1
    ppo_epoch: 5
    use_clipped_value_loss: true
    use_gae: true
    use_huber_loss: true
    use_max_grad_norm: true
    value_loss_coef: 0.001
  device:
    cuda: true
    cuda_deterministic: true
    torch_threads: 4
  logger:
    log_dir: ./results
  model:
    data_chunk_length: 10
    drop_prob: 0
    gain: 0.01
    hidden_dim: 256
    initialization_method: orthogonal_
    lr: 0.0005
    n_head: 2
    n_layers: 2
    n_rnn_layers: 2
    opti_eps: 1.0e-05
    rnn_hidden_dim: 1024
    weight_decay: 0
  render:
    render_episodes: 10
    use_render: false
  seed:
    seed: null
    seed_specify: false
  train:
    episode_length: 125
    eval_episodes: 20
    eval_interval: 5
    log_interval: 1
    model_dir: null
    n_eval_rollout_threads: 1
    n_rollout_threads: 8
    num_env_steps: 20000
    use_eval: false
    use_linear_lr_decay: false
    use_proper_time_limits: true
    use_valuenorm: true
env_args:
  task_name: battle_attack_city hard
run_times: 3
